name: pawsbase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  supabase_flutter: ^2.14.2
  widgetbook: ^3.23.0
  widgetbook_annotation: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  widgetbook_generator: ^3.23.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
